# Generated by Django 4.1.7 on 2023-04-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_service_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
