# Generated by Django 4.0 on 2023-04-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0004_murojaat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='murojaat',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
